export const stylesheet = {
  container: {
    position: "relative",
    width: "100%",
    height: "100%",
    overflow: "hidden",
  },
  scrollable___webkit_scrollbar: { display: "none" },
  horizontalSpacer: { position: "relative", height: "50%", width: "100%" },
  rowContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: "50%",
    paddingRight: "50%",
    boxSizing: "content-box",
  },
  row: { display: "flex", flexDirection: "row" },
  bubbleContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bubble: { width: "100%", height: "100%" },
  guideContainer: {
    position: "absolute",
    top: "0",
    left: "0",
    height: "100%",
    width: "100%",
    pointerEvents: "none",
  },
  guide: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    border: "2px solid rgba(0, 0, 0, 0.1)",
    backgroundColor: "rgba(0, 0, 0, 0.12)",
  },
  scrollable: {
    position: "absolute",
    top: "0",
    left: "0",
    height: "100%",
    width: "100%",
    overflow: "scroll",
    scrollPadding: "100px 0 0 100px",
    MsOverflowStyle: "none",
    scrollbarWidth: "none",
  },
};
